# Generated by Django 2.0.5 on 2018-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30, unique=True)),
                ('telefone', models.TextField(max_length=11)),
                ('endereço', models.TextField(max_length=80)),
                ('numero', models.IntegerField()),
                ('cidade', models.TextField(max_length=80)),
                ('estado', models.TextField(max_length=50)),
                ('país', models.TextField(max_length=30)),
                ('cep', models.TextField(max_length=8)),
            ],
        ),
    ]
