# Generated by Django 2.0.5 on 2018-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180515_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereço',
            new_name='logradouro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
